### ISSUE TITLE
Discord Group

### ISSUE THREAD

**Issue by TomyGamy** [naturecodevoid/voicechat-discord#30]
So my idea, add a thing in the config files to make a Voice Chat group linked to a discord Voice Chanel, so then the people in the VC group in game and in the Discord VC can hear each other...

**Comment by naturecodevoid** [comment]
So people not in the game would be able to chat? This might be possible, except for the big problem that there is no player to use to play audio in the group since the people in the VC wouldn't be on Minecraft.

Also, you might as well just use a normal VC

**Comment by TomyGamy** [comment]
yup

**Comment by TomyGamy** [comment]
maybe you could use somthing similar to https://modrinth.com/mod/audioplayer

**Comment by naturecodevoid** [comment]
I don’t think I’ll be adding this. It would be hard to add because groups require player / entity members, so we would have to create a fake player / entity. It’s also pretty pointless because you can just use a discord VC.

Also, both of those mods are SVC addons, which use the same API this mod does.
