### ISSUE TITLE
/dvc start giving error

### ISSUE THREAD

**Issue by Jeevanspeedx** [naturecodevoid/voicechat-discord#32]
**Describe the bug**
When I type **/dvc** start is says "Couldn't register an audio sender for you. this is most likely means you have the mod installed and working."

**To Reproduce**
1.Join appropriate voice channel in discord.
   Run **/dvc** start

**Expected behavior**
The bot should join the server and work fine but it does not.

**Screenshots**

![image_2023-09-19_141329889](https://github.com/naturecodevoid/voicechat-discord/assets/145438524/fb38fdef-93a8-4416-996f-d246b8f74dbd)

**Logs**
here are the logs: https://mclo.gs/3qxxDif

**Versions (please complete the following information):**
- Minecraft: 1.20.1
- Loader (paper,): 
- Simple Voice Chat: 2.4.24
- Simple Voice Chat Discord Bridge: 2.1.0

**Additional context**

**Comment by Jeevanspeedx** [comment]
sorry for reposting this I realized it is already closed. Very sorry

**Comment by naturecodevoid** [comment]
No problem, this error means you have SVC installed client side. SVC does not allow people who have it installed client side to use the addon

**Comment by asdfghjkl403622** [comment]
hey, I removed dvc from my client and I am still having this issue. 
[server logs](https://github.com/naturecodevoid/voicechat-discord/files/13753568/latest.log)
`[08:50:25] [Render thread/INFO]: [CHAT] Starting a voice chat... this might take a moment since we have to login to the bot.
[08:50:26] [Render thread/INFO]: [CHAT] Couldn't register an audio sender for you. This most likely means you have the mod installed and working.`
fabric modloader version 0.15.1, minecraft 1.20.1

**Comment by naturecodevoid** [comment]
Don't add discord voicechat to your client. It only goes on the server. Discord voicechat will only work if you do not have simple voice chat installed on your client.

**Comment by asdfghjkl403622** [comment]
sorry, I misunderstood the purpose of the mod. Is there any solution you know of for a simple bridge between ingame voicechat and discord? I just wanna talk with people who are not ingame without doing weird muting and annoying stuff.

**Comment by naturecodevoid** [comment]
That's been asked for before. You can't really do that without faking a player, which is sure to create many issues. You should just join a Discord call - there is no point in going through Simple Voice Chat.
