### ISSUE TITLE
[Paper] Plugin configuration folder not created

### ISSUE THREAD

**Issue by Finnchen1-de** [naturecodevoid/voicechat-discord#4]
The Plugin Folder was not created after a restart

**Comment by Finnchen1-de** [comment]
1.19.2 Paper Server

**Comment by naturecodevoid** [comment]
This actually is an issue with the paper version of the plugin that I missed during testing, which is caused by having to use my own configuration system instead of the Bukkit one. Sorry about that! If you weren't able to find a workaround, could you try [version 1.4.0](https://modrinth.com/mod/simple-voice-chat-discord-bridge/version/1.4.0)?
